<a href="https://colab.research.google.com/github/sylvia830/Health_Insurance_Prediction_Regression/blob/main/Insurance_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#import dataset
dataset = pd.read_csv('insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]


In [ ]:
#encoding categorical data - independent variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,4,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 19 27.9 0]
 [0.0 1.0 1.0 ... 18 33.77 1]
 [0.0 1.0 1.0 ... 28 33.0 3]
 ...
 [1.0 0.0 1.0 ... 18 36.85 0]
 [1.0 0.0 1.0 ... 21 25.8 0]
 [1.0 0.0 0.0 ... 61 29.07 0]]


In [ ]:
#split the dataset into training set and test test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train[:, 8:] = sc_X.fit_transform(X_train[:, 8:])
X_test[:, 8:] = sc_X.transform(X_test[:, 8:])
y_train = sc_y.fit_transform(y_train.reshape(len(y_train),1))

In [ ]:
print(X_test)

[[0.0 1.0 1.0 ... -1.4326502925452371 0.7937285808383426
  -0.9070577122378711]
 [0.0 1.0 1.0 ... 1.2887494222358575 0.14207029768743673
  -0.9070577122378711]
 [0.0 1.0 1.0 ... 0.8590547304283163 1.0338132114728866
  -0.9070577122378711]
 ...
 [0.0 1.0 0.0 ... 0.5725916025566221 1.3506595947592914 0.749173946626501]
 [1.0 0.0 1.0 ... -1.4326502925452371 0.9644009883302467
  -0.9070577122378711]
 [1.0 0.0 1.0 ... -0.28679778105846043 -0.7423230865887921
  -0.9070577122378711]]


In [ ]:
print(y_train)

[[-0.23802019]
 [-0.26205207]
 [-1.00098731]
 ...
 [ 2.60094183]
 [ 0.51454921]
 [-0.13877343]]


In [ ]:
print(y_test)

[ 1646.4297  11353.2276   8798.593   10381.4787   2103.08    38746.3551
  9304.7019  11658.11505  3070.8087  19539.243   12629.8967  11538.421
  6338.0756   7050.642    1137.4697   8968.33    21984.47061  6414.178
 28287.89766 13462.52     9722.7695  40932.4295   8026.6666   8444.474
  2203.47185  6664.68595  8606.2174   8283.6807   5375.038    3645.0894
 11674.13    11737.84884 24873.3849  33750.2918  24180.9335   9863.4718
 36837.467   17942.106   11856.4115  39725.51805  4349.462   11743.9341
 19749.38338 12347.172    4931.647   30259.99556 27724.28875 34672.1472
  9644.2525  14394.39815 12557.6053  11881.358    2352.96845  9101.798
 17178.6824   3994.1778  40941.2854  12644.589   22395.74424  1149.3959
  3366.6697  13143.33665 18328.2381   2690.1138  12741.16745  8765.249
 10264.4421  22192.43711  2709.24395 14571.8908  60021.39897 58571.07448
  1743.214   12479.70895 13352.0998  41034.2214   2789.0574   2867.1196
 11070.535   10493.9458   3167.45585 12269.68865 10942.13205  1977.8

In [ ]:
#training the multiple linear regression model on the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
#predicting the test results
y_pred = sc_y.inverse_transform(regressor.predict(X_test))

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 4384.85  1646.43]
 [12899.94 11353.23]
 [12640.47  8798.59]
 [13489.62 10381.48]
 [  374.98  2103.08]
 [31699.16 38746.36]
 [13206.57  9304.7 ]
 [12381.01 11658.12]
 [ 3818.75  3070.81]
 [29505.53 19539.24]
 [11295.99 12629.9 ]
 [17546.67 11538.42]
 [ 8913.65  6338.08]
 [ 8253.2   7050.64]
 [ 3464.94  1137.47]
 [10305.31  8968.33]
 [ 3795.17 21984.47]
 [ 6720.02  6414.18]
 [15329.45 28287.9 ]
 [14456.71 13462.52]
 [12664.06  9722.77]
 [32925.71 40932.43]
 [ 9055.18  8026.67]
 [ 8937.24  8444.47]
 [ 3063.96  2203.47]
 [ 8088.09  6664.69]
 [ 9456.16  8606.22]
 [11083.7   8283.68]
 [ 7569.16  5375.04]
 [ 4408.44  3645.09]
 [14126.49 11674.13]
 [ 5634.99 11737.85]
 [34223.02 24873.38]
 [26745.79 33750.29]
 [33232.35 24180.93]
 [ 9479.75  9863.47]
 [30165.98 36837.47]
 [26061.75 17942.11]
 [15565.32 11856.41]
 [33586.16 39725.52]
 [ 6507.73  4349.46]
 [14102.9  11743.93]
 [10847.83 19749.38]
 [15093.57 12347.17]
 [ 3983.87  4931.65]
 [13206.57 30260.  ]
 [ 4620.73 27724.29]
 [28679.96 34